# -*- coding: utf-8 -*-
"""4740_FA20_p1_pjc272_wh395.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_rR5LA-DbZfKAGiDqQ-Xpi0XIEv21UdD

# Project 1: Language Modeling and Fake News Classification

Names: Wesley Ho, Phil Cipollina

Netids: wh395, pjc272

**After you make your own copy, please rename this notebook by clicking on it's name in the upper left corner.** It should be named: 4740_FA20_p1_netid1_netid2

Don't forget to share your newly copied notebook with your partner!

**Reminder: both of you can't work in this notebook at the same time from different computers/browser windows because of sync issues. We even suggest to close the tab with this notebook when you are not working on it so your partner doesn't get sync issues.**

## Introduction
In this project we will build an **n-gram-based language model** for fake news classification. We will also investigate a feature-based **Naive Bayes model**. The task we are faced with is to **decide whether a news article is fake or real**. While some fake articles are so absurd and nonsensical that one can clearly guess they are fake, most fake news is actually quite hard to detect. [Various studies](https://pacscenter.stanford.edu/research/program-on-democracy-and-the-internet/deception-detection-accuracy-for-fake-news-headlines-on-social-media/) have shown that most people can have an error rate up to 50% depending on the theme of the article. 

To help us approach this problem, we will use NLP techniques covered thus far to frame this as a (supervised) binary classification task, where each article will have a label $y \in \{0,1\}$, where *0 indicates a fake article* and *1 indicates a real one*. You will train and validate your two different models and then run them on a test data set with hidden $y$ labels. You will then submit the results on the test data set to Kaggle to participate in our class-wide competition!

The project is divided into six parts:
1. Dataset loading and preprocessing
2. Unsmoothed n-gram language model (LM): build the unsmoothed n-gram language model using our Fake News corpus. 
3. Smoothed n-gram language model: build a smoothed version of the model from part 2.
4. Perplexity: compute perplexity for both the unsmoothed and smoothed model
5. Putting everything together and submitting the first model to Kaggle
6. Naive Bayes: build a feature-based Naive Bayes model to perform the same classification task. Compare the LM with Naive Bayes and identify the pros and cons of each.

**Logistics:** You should work in **groups of 2 students**. Students in the same group will get the same grade. Thus, you should make sure that everyone in your group contributes to the project. 
- **Remember to form groups on BOTH CMS and Gradescope** or not all group members will receive grades. You can use the Teammate Search option on Piazza to find a partner for this project.

**Advice:** Please complete the written parts of this notebook in a clear and informative way. This is where you get to show us that you understand not only what you are doing but also why and how you are doing it. So be clear, organized and concise; avoid vagueness and excess verbiage. Spend time
doing error analysis for the models. This is how you understand the advantages and drawbacks of the systems you build. 
- It's also useful to think about how the theory of n-grams/Naive Bayes bridges with the real world application we are building. Think about what you expect from these models based on your current understanding, and then see if your expectation aligns with empirical results that you'll get.

## General Guidelines
In this project, we provide a few code snippets or starter points in case you need them. You DO NOT need to follow the structure. 

If you think you have a better idea, go for it. You can ADD, MODIFY, or DELETE any code snippets given to you.

**Let's do this** 🚀

### Dataset

You are given a **News Corpus** on CMS, which consists of roughly the same amount of real and fake news articles.

Real news example:
```
The OpenAI technology, known as GPT-2, is designed to predict the next word given all the previous words it is shown within some text. The language-based model has been trained on a dataset of 8 million web pages.
```

Fake news example:
```
In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.
```

In the dataset folder you should find 4 files, training and validation splits for both real and fake news.

The project will proceed generally as follows in terms of code development:
1. Write code to train unsmoothed unigram and bigram language models for an arbitrary corpus
2. Implement smoothing and unknown word handling. 
3. Implement the Perplexity calculation. 
4. Using 1, 2 and 3, together with the provided training and validation sets, develop a language-model-based approach for Fake News Classification.
5. Apply your best language-model-based news classifier (from 4) to the
provided test set. Submit the results to the online Kaggle competition. 
6. Use any existing implementation of Naive Bayes (and the provided training and validation sets) to create an additional Naive Bayes fake news classifier. Apply your best NB classifier to the provided test set. Submit the results to the separate Kaggle competition (for NB classifiers). 

We will progress towards these tasks throughout this notebook.

# Part 1: Preprocessing the Dataset
In this part, you are going to do a few things:
* Connect to the google drive where the data set is stored
* Load and read files
* Preprocess the text

------
**Please upload the dataset to each partner's individual Google Drive now.** We suggest using the same folder structure within Google Drive because the notebook is shared among you, so the code to load the data would have to be changed every time if folder structures are different. One folder structure might be: Google Drive/CS 4740/Project 1/Dataset/ or whatever works for you. See our code below for an example of how we load the data from Google Drive.

## 1.1 Connect to google drive
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

"""## 1.2 Load and read files
First, let's install [NLTK](https://www.nltk.org/), a very widely package for NLP preprocessing (and other tasks) for Python.
"""

!pip install -U nltk

"""Then we read and load data."""

import time
s = time.time()
import os
import io
from nltk import word_tokenize, sent_tokenize
import nltk
nltk.download('punkt')


root_path = os.path.join(os.getcwd(), "drive", "My Drive/CS 4740/Project 1") # replace based on your Google drive organization
dataset_path = os.path.join(root_path, "Dataset") # same here

with io.open(os.path.join(dataset_path, "trueDataTrain.txt"), encoding='utf8') as real_file:
  real_news = real_file.read()
with io.open(os.path.join(dataset_path, "trueDataValidation.txt"), encoding='utf8') as real_file:
  real_news_validation = real_file.read()
with io.open(os.path.join(dataset_path, "fakeDataTrain.txt"), encoding='utf8') as fake_file:
  fake_news = fake_file.read()
with io.open(os.path.join(dataset_path, "fakeDataValidation.txt"), encoding='utf8') as real_file:
  fake_news_validation = real_file.read()

tokenized_real_news_training = [list(map(str.lower, word_tokenize(sent))) for sent in sent_tokenize(real_news)]
tokenized_fake_news_training = [list(map(str.lower, word_tokenize(sent))) for sent in sent_tokenize(fake_news)]
tokenized_real_news_validation = [list(map(str.lower, word_tokenize(sent))) for sent in sent_tokenize(real_news_validation)]
tokenized_fake_news_validation = [list(map(str.lower, word_tokenize(sent))) for sent in sent_tokenize(fake_news_validation)]

print('this cell done in: ' + str(time.time() - s) + " seconds.")

print(dataset_path)

small_train_set_corpus = "i see what i eat and i eat what i see."
# small_train_set = " For graphic showing Trump's ascendancy on PredictIt during primary season, see tmsnrt.rs/1WmRq For November’s election, though, Trump is trailing on PredictIt with 40 cents against Clinton’s 59 cents.  While PredictIt’s precision has yet to be closely examined by academics, other predictions markets such as the Iowa Electronic Markets, have proven to be just as accurate as polls, experts who have studied them said. "
small_train_set = [list(map(str.lower, word_tokenize(sent))) for sent in sent_tokenize(small_train_set_corpus)]
small_validate_set_corpus = "i see and i eat"
small_validate_set = [list(map(str.lower, word_tokenize(sent))) for sent in sent_tokenize(small_validate_set_corpus)]
print(small_train_set)

"""Sanity checks for our real and fake training sets"""

tokenized_real_news_training[2]

print(ord("’"))
print(ord("'"))

tokenized_fake_news_training[50]

tokenized_real_news_validation[0]

"""## 1.3 Data Preprocessing & Preparation

There's a well-known parable in machine learning that 80% of the work is all about data preparation, 10% is supporting infrastructure and 10% is actual modeling. If your "raw" dataset is not preprocessed and prepared in a way to maximize its value, then your model will be more like this: https://xkcd.com/1838/. For this project, modeling is the star of the show for learning purposes, but we still want you to pay attention to the preprocessing stage.

*We've already tokenized and lowercased* the raw data for you. Here are a few extra things you might want to do:

- Think about edge cases. For example, you don't want to accidentally append a period to the last word of a sentence. 
- Watch out for apostrophes and other tricky things like quotations, they cause lots of edge cases. For example, "they're" can be all one token, or two tokens ("they", "'re") or even three tokens ("they", " ' ", "re"). 

Why did we lowercase all tokens? Because the computer will otherwise consider "The" and "the" as two separate words and this will cause problems.

Note that you may use existing
tools just for the purpose of preprocessing. 

Advice: don't get bugged down in the dozens of preprocessing packages and suggestions that you can find on Towards Data Science or Stack Overflow. Start with this [NLTK tutorial](https://lost-contact.mit.edu/afs/cs.pitt.edu/projects/nltk/docs/tutorial/introduction/nochunks.html#:~:text=The%20Natural%20Language%20Toolkit%20(NLTK,tokenization%2C%20tagging%2C%20and%20parsing.) and that should be plenty.
"""

import copy
ogtfnt = copy.deepcopy(tokenized_fake_news_training)
ogtfnv = copy.deepcopy(tokenized_fake_news_validation)
ogtrnt = copy.deepcopy(tokenized_real_news_training)
ogtrnv = copy.deepcopy(tokenized_real_news_validation)

from nltk.tokenize import RegexpTokenizer
ex_text = "hello.thisis a. test.did it work?"
regexp = r'\w+|[^\w\s]+'
tokenizer = RegexpTokenizer(regexp)
tokenizer.tokenize(ex_text)

def apos(lst): # apos = apostrophe
  for a in lst: # a = sentence
    for i in range(len(a)): # i = word index
      b = a[i]
      if b[0] == "'" and b[-1] != "'":
        c = b[1:]
        b = b[0]
        a.insert(i, b)
        a[i+1] = c
      elif  b[0] == "’" and b[-1] != "’":
        c = b[1:]
        b = b[0]
        a.insert(i, b)
        a[i+1] = c

apos(tokenized_fake_news_training)
apos(tokenized_fake_news_validation)
apos(tokenized_real_news_training)
apos(tokenized_real_news_validation)
print('done')

"""**Q1.1: Show some observations or statistics from the dataset** (should be quantitative – i.e. most frequent words, most frequent bigram, etc.)

Your answer: We found the following:
- longest word(s)
- most frequent words (tokens actually)


"""

def getLongestWord(ts):
  sts = []
  for i in ts:
    sts.append(set(i))
  c = 0
  mw = ""
  for k in sts:
    for w in k:
      if len(w) > c:
        c = len(w)
        mw = w
      elif len(w) == c:
        mw += ", " + w
  return mw
lw1 = getLongestWord(tokenized_real_news_training)
lw2 = getLongestWord(tokenized_fake_news_training)
lw3 = getLongestWord(tokenized_fake_news_validation)
lw4 = getLongestWord(tokenized_real_news_validation)
print("The longest word(s) in real news training are:", len(lw1), "long. They are:", lw1 + ".")
print("The longest word(s) in fake data news training are:", len(lw2), "long. They are:", lw2 + ".")
print("The longest word(s) in fake data news verification are:", len(lw3), "long. They are:", lw3 + ".")
print("The longest word(s) in real data news verification are:", len(lw4), "long. They are:", lw4 + ".")

# most frequent word, start word, bigram, frequency distribution

def getMFW(ts):
  d = {}
  for i in ts: # i = sentence
    for j in i: # j = word
      if j in d:
        d[j] += 1
      else:
        d[j] = 1
  m = ''
  for i in range(10):
    t = max(d, key=d.get)
    m += t
    d[t] = 0
    if i < 9:
      m += ', '
  return m

mfw1 = getMFW(tokenized_real_news_training)
mfw2 = getMFW(tokenized_fake_news_training)
mfw3 = getMFW(tokenized_fake_news_validation)
mfw4 = getMFW(tokenized_real_news_validation)
print("The most frequent tokens in real news training are:", mfw1 + ".")
print("The most frequent tokens in fake data news training are:", mfw2 + ".")
print("The most frequent tokens in fake data news verification are:", mfw3 + ".")
print("The most frequent tokens in real data news verification are:", mfw4 + ".")

"""**Please answer the following question**:

**Q1.2: What did you do in your preprocessing part?**

Your answer: We tokenized and lowercased all the words (given). Then we searched for apostrophies. This includes both the apostrophe ' as well as the apostrophe ’. The former, ', has the unicode designation 39 as it is a real apostrophe and was in ascii. The latter, ’, has the unicode designation 8217 because its not an apostrophe, it's actually a "Right Single Quotation Mark", that for some reason the corpus uses as an apostrophe. This was found by manual inspection.

# Part 2: Compute Unsmoothed Language Models.

To start, you will write a program that computes unsmoothed unigram and bigram probabilities. You should consider real and fake news as separate corpora and
generate a separate language model for each set of news.
We have already loaded the data and (partially) preprocessed it and you probably did some of your own preprocessing. 

Note that you were allowed to use existing
tools for the purpose of preprocessing, but you must write the code for gathering n-gram counts and computing n-gram probabilities yourself. 

For example, consider the
simple corpus consisting of the sole sentence:


> the students liked the assignment

Part of what your program would compute for a unigram and bigram model, for example,
would be the following:


> $P("the") = 0.4; P("liked") = 0.2; P("the"|"liked") = 1.0; P("students"|"the") = 0.5$

Remember to add a symbol to mark the beginning of sentence. See Sept. 7th lecture, p25-28 for an example.

**Advice**: jupyter notebooks (including colab) can be a double-edged sword. It's amazing and liberating to just start writing code and run it by simply running a cell. However, it gets messy very quickly. So, once you're done prototyping, we highly recommend using functions (classes may be unnecessary but go for it if you want) to make things cleaner and easier to debug.

## 2.1 Unsmoothed Uni-gram Model.

In this part of the project, you are trying to compute the probabilities for a unigram model. You might want to take in a list of words, and return the probabilities for each
occurence. Think of an efficient data structure to use here given what ratio of reads and puts you expect.

Please look at the example above and consider how we get the probabilities.

Below is a starter point you can go from, but you DO NOT need to stick it. Feel free to use your own design.
"""

def bow(lst):
  d = {}
  for j in lst:
    for i in j:
      if i in d:
        d[i] += 1
      else:
        d[i] = 1
  return d

"""
Reference code for start. You do not need to follow this.
Function [unsmoothed_unigram] computes the probabilities for a unigram model
lst: a list of words in a sentence
Return: [data structure of your choice] that stores the result
"""
def unsmoothed_unigram(lst):
  boww = bow(lst)
  # print(boww)
  N = 0
  for sent in lst:
    N += len(sent)
  for w in boww:
    boww[w] = boww[w] / N
  return boww

t = small_train_set
# print(t)
uut = unsmoothed_unigram(t)
print(len(uut), uut)
# ful = 0
# for i in uut:
#   ful += uut[i]
# print(ful)

"""## 2.2 Unsmoothed Bi-gram Model.

In this part of the project, you are trying to compute the probabilities for a bigram model. You can approach this with similar methods as above.

Remember the definition:
$p(w_n\mid w_{n-1})=\frac{C(w_{n-1}w_n)}{C(w_{n-1})}$ this means you might want to store two things (count of $w_{n-1}$ and count of $w_{n-1}w_n$).
"""

def bibow(lst):
  d = {"<s>":1}
  d2 = {}
  d3 = {}
  for j in lst:
    store = None
    for i in j:
      if i in d:
        d[i] += 1
      else:
        d[i] = 1
      if store == None:
        t = "<s>" + " " + str(i)
      else:
        t = str(store) + " " + str(i)
      store = i
      if t in d2:
        # print(t)
        d2[t] += 1
      else:
        # print(t)
        d2[t] = 1
  # for i in d2:
  #   j, k = i.split(" ")
  #   d3[i] = d2[i] / d[j]
  return d2 #d3

def unsmoothed_bigram(lst):
  d = {"<s>":1}
  d2 = {}
  d3 = {}
  for j in lst:
    store = None
    for i in j:
      if i in d:
        d[i] += 1
      else:
        d[i] = 1
      if store == None:
        t = "<s>" + " " + str(i)
      else:
        t = str(store) + " " + str(i)
      store = i
      if t in d2:
        # print(t)
        d2[t] += 1
      else:
        # print(t)
        d2[t] = 1
  for i in d2:
    j, k = i.split(" ")
    d3[i] = d2[i] / d[j]
  return d3
bug = unsmoothed_bigram(small_train_set)
print(bug)
# count =0
# for i in unsmoothed_bigram(t):
#   count += unsmoothed_bigram(t)[i]
# print(count)

"""**Please answer the following question**:

**Q2: What data structure are you using to store probabilities for unigrams and bigrams? Why did you select this data structure?**

Your answer: dictionary. because it's a hash that can quickly store the value and the count of each value

# Part 3: Smoothed Language Model
In this part, you will need to implement **at least one** smoothing method and **at least one** method to handle unknown words in the test data. You can choose any method(s) that you want for each. You should make clear
**what method(s)** were selected and **why**, providing a description for any non-standard approach (e.g., an approach that was not covered in class or in the readings). 

You should use the
provided validation sets to experiment with different smoothing/unknown word handling
methods if you wish to see which one is more effective for this task. (We will cover this in Part 4).

## 3.1 Unknown Words Handling

**Please answer the following questions:**

**Q3.1: How are you going to handle unknown words? What parameters might be needed? Do you need a method to determine the value?**

Your answer: We are going to handle unknown words by using an add unk method. The parameter for this method will be the tokenized data set. We wil be using a method for this.
"""

def addunk(lst):
  c = 0
  s = set()
  for i in lst:
    for j in range(len(i)):
      c += 1
      if i[j] not in s:
        s.add(i[j])
        if (c % 10 in {1,2,3,4}):
          i[j] = "<unk>"
  return lst

"""## 3.2 Smoothing

In this part of project, we are going to compute the probabilities for unigram and bigram models after smoothing.
There are several smoothing methods you can start with:
* add-k
* Kneser-Ney
* Good-Turing
* ...

You need to compute for both unigram and bigram models.

Below is a starter point using add-k smoothing. As always, you DO NOT need to follow it; you DO NOT need to use add-k smoothing if you do not want to. You can pick ANY smoothing method you want.
"""

"""
Reference code for add-k smoothing on unigram model.
dic: a dictionary of your unigrams. key: words, val: occurence
k: parameter k for smoothing
Return: a dictionary of results after smoothing
"""
import copy
def add_k_unigram(dicc, k):
  dic = copy.deepcopy(dicc)
  count = 0
  for i in dic:
    count += dic[i]
  for i in dic:
    dic[i] = (dic[i] + k) / (len(dic) * k + count)
  return dic

aku = add_k_unigram(uut, 1)
print(aku)

"""
Reference code for add-k smoothing on bigram model.
uni_dic: a dictionary of your unigrams.
bi_dic: a dictionary of your bigrams.
k: parameter k for smoothing
Return: a dictionary of results after smoothing
"""
def add_k_bigram(uni_dic, bi_dic, k, n):
  bd = {}
  uni_dic["<s>"] = n
  lu = len(uni_dic)
  # print(lu)
  for i in bi_dic:
    j, m = i.split()
    p = (bi_dic[i] + k) / (uni_dic[j] + lu*k)
    bd[i] = p
  # bd["<unk>"] = k / (lu*k + uni_dic[j])
  # for j in uni_dic:
  #   for i in range(len(uni_dic)-1):
  #     if i != 0:
  #       t = str(j[i]) + " " + str(j[i-1])
  #     else:
  #       t = "<s> " + str(j[i])
  #     if t in bi_dic:
  #       bd[t] = (bi_dic[t] + k) / (uni_dic[j] + lu*k)
  #     print(t)
  return bd

print(bug)
akb = add_k_bigram(uut, bug, 1, 1)
print(akb)

"""**Please answer the following question:**

**Q3.2: Which smoothing method did you choose? Are there any parameters, if so how are you planning to pick the value? If you choose to implement more than 1 method (not a requirement), please state each of them. Providing a description for any non-standard approach, e.g., an approach that was not covered in class or in the readings**

Your answer: We chose Add-k smoothing. The only parameter is k. We will use perplexity to determine the best value of k by comparing how good different values of k are in evaluating a model. The code for this can be seen in part 5.

# Part 4: Perplexity
At this point, we have developed several language models: unigram vs bigram, unsmoothed vs smoothed. We now want to compare all the models. 

Implement code to compute the perplexity of a **“development set.”** (“Development set”
is just another way to refer to the validation set—part of a dataset that is distinct from
the training portion and the test portion.) Compute and report the perplexity of each
of the language models (one trained on true news and fake news) on
the development corpora. Compute perplexity as follows:
\begin{align*}
PP &= \left(\prod_i^N\frac{1}{P\left(W_i\mid W_{i-1}, ...W_{i-n+1}\right)}\right)^{\frac{1}{N}}\\
&=\exp \frac{1}{N}\sum_{i}^N-\log P\left(W_i\mid W_{i-1}, ...W_{i-n+1}\right)
\end{align*}
where $N$ is the total number of tokens in the test corpus and $P\left(W_i\mid W_{i-1}, ...W_{i-n+1}\right)$
is the n-gram probability of your model. Under the second definition above, perplexity
is a function of the average (per-word) log probability: use this to avoid numerical
computation errors.

Please complete the following tasks and report what you have observed. Remember, lower perplexity means better model.

## Task 1: Compute perplexity for smoothed unigram and smoothed bigram. 
*Note: If you choose more than one smoothing method, pick one of them to compute. If you need to try different values of parameters, you can try them out here.*
"""

def precompute_cup(lstt, k):
  lst = copy.deepcopy(lstt)
  # lst2 = copy.deepcopy(lstt2)
  lst = addunk(lst)
  N = 0
  for i in lst:
    N += len(i)
  unsmoothed_gram = bow(lst)
  smoothed_unigram = add_k_unigram(unsmoothed_gram, k)
  return (smoothed_unigram, N)

pc_cup = precompute_cup(tokenized_fake_news_training, 1)

def precompute_cbp(lstt, k):
  lst = copy.deepcopy(lstt)
  # lst2 = copy.deepcopy(lstt2)
  lst = addunk(lst)
  N = 0
  for i in lst:
    N += len(i) + 1
  unsmoothed_ugram = bow(lst)
  lu = len(unsmoothed_ugram)
  unsmoothed_bgram = bibow(lst)
  smoothed_bigram = add_k_bigram(unsmoothed_ugram, unsmoothed_bgram, k, len(lst))
  
  return (unsmoothed_ugram, smoothed_bigram, N, lu)

pc_cbpf = precompute_cbp(tokenized_fake_news_training, 1)

pc_cbpr = precompute_cbp(tokenized_real_news_training, 1)

import math
import copy
timess = time.time()
# def concat_dict(d1, d2):
#   for i in d2:
#     if i in d1:
#       d1[i] += d2[i]
#     else:
#       d1[i] = d2[i]
#   return d1

def compute_unigram_perplexity(su, k, lst2):
  smoothed_unigram, N = su
  p = 0
  for j in lst2:
    for i in j:
      sui = smoothed_unigram["<unk>"]
      if i in smoothed_unigram:
        sui = smoothed_unigram[i]
      p += -1 * math.log(sui)
  print("cup p:" + str(p))
  print("cup N:" + str(N))
  PP = math.exp(1/N * p)
  return PP
# cup = compute_unigram_perplexity(pc_cup, 1, tokenized_fake_news_validation)
# cup = compute_unigram_perplexity(small_train_set, 1, small_validate_set)
# print("cup:" + str(cup))

def compute_bigram_perplexity(sb, k, lstt2):
  lst2 = lstt2
  unsmoothed_ugram, smoothed_bigram, N, lu = sb
  unsmoothed_bgram2 = bibow(lst2)
  p = 0
  s1 = 0
  s2 = 1
  for i in unsmoothed_bgram2:
    # sub = smoothed_bigram["<unk>"]
    # sub = 1
    if i in smoothed_bigram:
      sub = smoothed_bigram[i]
    else:
      j, doesntmatter = i.split()
      if j in unsmoothed_ugram:
        sub = k / (lu*k + unsmoothed_ugram[j])
      else:
        sub = k / (lu*k + unsmoothed_ugram["<unk>"])
    p += -1 * math.log(sub)
  #   print(i, sub, p)
  # print("p:" + str(p))
  # print("N:" + str(N))
  PP = math.exp(1/N * p)
  return PP
# t = tokenized_real_news_training[0]
# cbp = compute_bigram_perplexity(small_train_set, 1, small_validate_set)
# cbp = compute_bigram_perplexity(tokenized_fake_news_training, 1, tokenized_fake_news_validation)
cbp = compute_bigram_perplexity(pc_cbp, .0023, tokenized_real_news_validation)
print("cbp:" + str(cbp))
print('this cell done in: ' + str(time.time() - timess) + " seconds.")

pccbp =precompute_cbp(tokenized_fake_news_training, 0.1)
compute_bigram_perplexity(pccbp, 0.1, tokenized_fake_news_validation)

"""**Q4.1: Why do we need to compute perplexity after smoothing?**

Your answer: We need to compute perplexity after smoothing in order to compare the models.

**Q4.2: Did you choose any values for parameters?**

Your answer: We chose to use k as a parameter.

## Task 2: Compute perplexity for other smoothing methods (optional). 
*Note: If you only pick one smoothing method, you can omit this task. If you need to try different values of parameters, you can try them out here.*
"""

# TODO: compute perplexity for your rest of smoothing method.

"""**Q4.3: If your smoothing method needs to pick a parameter, what is the value of your parameter?**

Your answer:

**Q4.4: Which smoothing method is the best among your choices?**

Your answer:

# Part 5: Putting Everything Together and Submitting to Kaggle
Combining all the previous parts together, we have developed a bunch of language models. Before we proceed to the next step, let's check a few things (no need to answer):
* Did you train your model only on training set?
* Did you validate your model only on validation/development set?
* Did you determine all your parameters?

Finally, please answer:

**Q5: What is your choice of language model, and why?**

Your answer: k-smoothed bigram model, k = .0023 for fake, .0067 for real
"""

min_p = 10000
mink = 10000
k = 0.006
timestart = time.time()
while k < .007:
  pc_cbp = precompute_cbp(tokenized_real_news_training, k)
  cbp = compute_bigram_perplexity(pc_cbp, k, tokenized_real_news_validation)
  if min_p > cbp:
    min_p = cbp
    mink = k
  k += 0.0001
print(min_p, mink)
print('time', str(time.time()-timestart))

"""## Part 5.1: First Model Submission to Kaggle

Now we need to apply our model to testing data. What you need to do:
* Takes the test data as input, and generates an output of your prediction based on your chosen language model
* Your output file should be ONLY your predictions
* Submit to Kaggle

You should use your trained model to predict labels for all the news in `TestData.txt`. Output your predictions to a **csv** file and submit it to kaggle. Each line should contain the id of the test news and its corresponding prediction (in total 4489 lines). In other words, your output should look like (**including the header**):
```
Id,Prediction
0,0
1,0
2,1
3,0
...
4488,1
```
Note that you should add the header `Id,Prediction` and there is no space in the output. The Id starts from 0 (not 1).

Use this kaggle [link](https://www.kaggle.com/t/a032d54898b24b4bb2f29e7165ac5fdf) to submit your output. Your team name should be the concatenation of your netids, **exactly in the same order as this notebook is named**. For example, if notebook is 4740_FA20_p1_jb123_cj456, then Kaggle group should be jb123_cj456.

"""

with io.open(os.path.join(dataset_path, "TestData.txt"), encoding='utf8') as real_file:
  testData = real_file.readline()
# print(testData[0])

testDatatxt = open(os.path.join(dataset_path, "TestData.txt"), 'r')
testData = []
while True:
  line = testDatatxt.readline()
  if not line:
    break
  testData.append(line)

print(testData[0])
print(len(testData))
print('celll done')

timezz = time.time()
tokenized_real_val_data = []
for line in real_news_validation:
  tokenized_real_val_data.append([list(map(str.lower, word_tokenize(sent))) for sent in sent_tokenize(line)])
print('t', str(time.time()-timezz))

timezz = time.time()
apos(tokenized_real_val_data)
pcfake = precompute_cbp(tokenized_fake_news_training, .0067)
pcreal = precompute_cbp(tokenized_real_news_training, .0067)
print('done')
print('t', str(time.time()-timezz))

timestart = time.time()
id = 0
pcount = 0
count = 0
file = [
     ["Id", "Prediction"],
]
for line in tokenized_real_news_validation:
  count += 1
  # prediction = -420
  fake = compute_bigram_perplexity(pcfake, .0067, line)
  real = compute_bigram_perplexity(pcreal, .0067, line)
  if fake - real < 0:
    pcount += 1
    # prediction = 1
  # else:
    # prediction = 0
  # file.append([id, prediction])
  id += 1
print('time taken is:', str(time.time()-timestart))
print('p', str(pcount/count))

tokenized_testData = []
for line in testData:
  tokenized_testData.append([list(map(str.lower, word_tokenize(sent))) for sent in sent_tokenize(line)])

print(tokenized_testData[0])
print(len(tokenized_testData))
print(tokenized_testData[-1])

apos(tokenized_testData)
print('done')

pcfake = precompute_cbp(tokenized_fake_news_training, .0023)

pcreal = precompute_cbp(tokenized_real_news_training, .0067)

timestart = time.time()
count = 0
pcount = 0
id = 0
file = [
     ["Id", "Prediction"],
]
for line in tokenized_testData:
  count += 1
  prediction = -420
  fake = compute_bigram_perplexity(pcfake, .0023, line)
  real = compute_bigram_perplexity(pcreal, .0067, line)
  if fake - real > 0:
    prediction = 1
    pcount += 1
  else:
    prediction = 0
  file.append([id, prediction])
  id += 1
print('time taken is:', str(time.time()-timestart))
print('p', str(pcount/count))

print(file)

import csv
# output_file (.write?) google 
t = [
     [0,0],
     [1,0],
     [2,1],
     [3,0]
]
root_path = os.path.join(os.getcwd(), "drive", "My Drive/CS 4740/Project 1") # replace based on your Google drive organization
dataset_path = os.path.join(root_path, "Dataset") # same here
with open(os.path.join(dataset_path, "4740_FA20_p2_pjc272_wh395_output.csv"), encoding='utf8', mode='w') as real_file:
  output_file = csv.writer(real_file, delimiter=',')

  # output_file.writerow(['Id','Prediction'])
  for i in file:
    output_file.writerow(i)
print('cell done')

"""# Part 6: Naive Bayes

The Naive Bayes classification method is based on Bayes Rule. Suppose we have a news article *d* and its label *c* (either 0 or 1).
\begin{align*}
P(c|d)=\frac{P(d|c)P(c)}{P(d)}
\end{align*}
Likelihood: $P(d|c)$. In real/fake corpus, how likely *d* would appear.

Prior: $P(c)$. The probability of real/fake news in general.

Posterior: $P(c|d)$. Given *d*, how likely is it that it is real/fake.

Goal: $\underset{c\in \{0,1\}}{\operatorname{argmax}} P(c|d)$, which is equivalent to $\underset{c\in \{0,1\}}{\operatorname{argmax}} P(d|c)P(c)$.

The equivalence holds because $P(d)$ is the same for any $c$. Thus the denominator can be dropped.

Denote $d=\{x_1, x_2, ..., x_n\}$ where $x_i$'s are words in the news *d* (sometimes called features). Unlike n-gram language modelling, we make the multinomial Naive Bayes independence assumption here, where we assume positions of words do not matter. Formally, 
\begin{align*}
&\underset{c\in \{0,1\}}{\operatorname{argmax}} P(d|c)P(c)\\
=&\underset{c\in \{0,1\}}{\operatorname{argmax}} P(x_1, ..., x_n|c)P(c)\\
=&\underset{c\in \{0,1\}}{\operatorname{argmax}} P(x_1|c)P(x_2|c)...P(x_n|c)
\end{align*}

Now we only need to collect the occurences of each word for the classification. This is often called a **bag of words** feature. 

For instance, in the sentence `All for one and one for all .`, the bag of words feature would be `{"all": 2, "for": 2, "one": 2, "and": 1, ".": 1}`. Essentially, the bag of words feature is a dictionary which maps the word to its occurences. We can see that the order is not considered here.

Now, your goal is to implement the Multinomial Naive Bayes. You can use existing codes or Python packages, and adapt them to our news classification task.

You might find the following packages/functions useful:

* nltk.word_tokenize(), nltk.word_tokenize()
* nltk.classify.naivebayes()
* sklearn.feature_extraction.text
* sklearn.naive_bayes.MultinomialNB()

**Please answer the following question(s).**

**Q6: Comparing Multinomial Naive Bayes with the unigram language model, which one do you expect to perform better? Why?**

A: We expect multinomial Naive Bayes to outperform the unigram language model because it takes into account prior bias.

## 6.1 Implementation
"""

import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import random as rand

x = rand.random()
print(x)

def nbaddunk(lst):
  c = 0
  s = set()
  for i in lst:
    for j in range(len(i)):
    c += 1
      if i[j] not in s:
        s.add(i[j])
        if .4 > rand.random():
          i[j] = "<unk>"
  return lst

def smooth_nb(ts, k): # tokenized ts
  dic = copy.deepcopy(ts)
  count = 0
  for i in dic:
    count += dic[i]
  for i in dic:
    dic[i] = (dic[i] + k) / (len(dic) * k + count)
  return dic

def prenb(trt, tft, k):
  # trt = tokenized_real_news_data, tft = fake
  nbaddunk(trt)
  nbaddunk(tft)
  realbow = bow(trt)
  fakebow = bow(tft)
  # trt2 = smooth_nb(realbow, k)
  # tft2 = smooth_nb(fakebow, k)
  
  return (realbow, fakebow)

def nb(line, pren):
  trt, tft = pren
  p_real = 0; p_fake = 0
  for sent in line:
    for word in sent:
      if word in trt:
        p_real += -math.log(trt[word])
        if(trt[word]==0):
          print("fuck")
      else:
        p_real += -math.log(trt["<unk>"])
        if(trt["<unk>"]==0):
          print("fucc")
      if word in tft:
        p_fake += -math.log(tft[word])
        if(tft[word]==0):
          print("fuc")
      else:
        p_fake += -math.log(tft["<unk>"])
        if(tft["<unk>"]==0):
          print("fucck")
  # if(p_real ==0 or p_fake ==0):
  #  print(p_real, p_fake)
  # return (p_real, p_fake)
  if p_real > p_fake:
    return 1
  else:
    return 0

def rnb(line, pren):
  trt, tft = pren
  p_real = 1; p_fake = 1
  for sent in line:
    for word in sent:
      if word in trt:
        p_real *= trt[word]
      else:
        p_real *= trt["<unk>"] 
      if word in tft:
        p_fake *= tft[word]
      else:
        p_fake *= tft["<unk>"]
  if(p_real ==0 or p_fake ==0):
    print(p_real, p_fake)
  # return (p_real, p_fake)
  if p_real > p_fake:
    return 1
  else:
    return 0

def rrnb(line, pren):
  trt, tft = pren
  p_real = 0; p_fake = 0; pppppp = 0
  for sent in line:
    for word in sent:
      if word in trt:
        p_real += -math.log(trt[word])
        pppppp = 1
        if(trt[word]==0):
          print("fuck")
      # else:
      #   p_real += -math.log(trt["<unk>"])
      #   pppppp = 1
      #   if(trt["<unk>"]==0):
      #     print("fucc")
      if word in tft:
        p_fake += -math.log(tft[word])
        pppppp = 1
        if(tft[word]==0):
          print("fuc")
      # else:
      #   p_fake += -math.log(tft["<unk>"])
      #   pppppp = 1
      #   if(tft["<unk>"]==0):
      #     print("fucck")
    if pppppp == 0:
      print(word, sent)
  # if(p_real ==0 or p_fake ==0):
  print(p_real, p_fake, pppppp, len(line))
  # return (p_real, p_fake)
  if p_real > p_fake:
    return 1
  else:
    return 0

"""## 6.2 Putting Everything Together and Submitting to Kaggle

You should use your trained model to predict labels for all the news in `TestData.txt`. Output your predictions to a **csv** file and submit it to kaggle. The format should follow Part 6 as well.

Use this Kaggle [link](https://www.kaggle.com/t/e8e4f7ee507843d1902c168529d705c8) to submit your output.
"""

apos(testData)
print('this cell done')

pren = prenb(tokenized_real_news_training, tokenized_fake_news_training, .05)
print('done')

max_p_r = 10000
max_p_f = -10000
maxk_r = 10000
maxk_f = 10000
k = 10

timestart = time.time()
while k < 11:
  actualp_r = 0
  actualp_f = 0
  pren = prenb(tokenized_real_news_training, tokenized_fake_news_training, k)
  for line in tokenized_fake_news_validation:
    curp = nb(line, pren)
    actualp_r += curp
    actualp_f += (1-curp)
  if max_p_f < actualp_f:
    max_p_f = actualp_f
    maxk_f = k
  if max_p_r > actualp_r:
    max_p_r = actualp_r
    maxk_r = k
  k += 1
print("real:" + str(max_p_r) + "," + str(maxk_r))
print("fake:" + str(max_p_f) + "," + str(maxk_f))
print('time', str(time.time()-timestart))

timestart = time.time()
count = 0
pcount = 0
id = 0
file = [
     ["Id", "Prediction"],
]
for line in tokenized_testData:
  count += 1
  prediction = -420
  if rnb(line, pren) > 0:
    prediction = 1
    pcount += 1
  else:
    prediction = 0
  file.append([id, prediction])
  id += 1
print('time taken is:', str(time.time()-timestart))
print('p', str(pcount/count))

import csv
# output_file (.write?) google 
t = [
     [0,0],
     [1,0],
     [2,1],
     [3,0]
]
root_path = os.path.join(os.getcwd(), "drive", "My Drive/CS 4740/Project 1") # replace based on your Google drive organization
dataset_path = os.path.join(root_path, "Dataset") # same here
with open(os.path.join(dataset_path, "4740_FA20_p2_pjc272_wh395_output.csv"), encoding='utf8', mode='w') as real_file:
  output_file = csv.writer(real_file, delimiter=',')

  # output_file.writerow(['Id','Prediction'])
  for i in file:
    output_file.writerow(i)
print('cell done')

"""# Work Distribution

**Please briefly describe how you divided the work.**

Your answer: We took turns pair programming, with one partner typing up code while the other dictated the code and ideas for what to implement. All work was done together.

# Project Feedback [1 point]
It goes without saying that this is an unprecedented time. We on the course staff are trying our best to adapt our teaching, projects and everything else in the class to this new modality. We would immenselly appreciate it if you could provide us feedback (it's a super short form!!) on this project and **it's worth 1 point of your project grade**

Link to the feedback form: https://forms.gle/xfonP9rJk9Uk7zaSA 

We will use this feedback to improve both **upcoming projects** and projects for next year. 

Thank you so much!

# Submitting the Notebook

1. Go to File (upper left corner) -> Download .ipynb -> submit this downloaded file to cms
2. Run the first code block
3. Replace our placeholder for your correct Google Drive directory structure in the 2nd code block below. Run the code block
4. Put the name of this notebook into our placeholder in the 3rd code block. Run the code block
5. Then go to the folder icon on the very left panel, under the orange CO logo. Click on the folder and wait for a PDF version of your notebook to appear. Might take a few minutes.
6. Download the pdf version and submit to Gradescope
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !apt-get install texlive texlive-xetex texlive-latex-extra pandoc
# !pip install pypandoc

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # the red text is a placeholder! Change it to your directory structure!
# !cp 'My Drive/CS 4740/Project 1/4740_FA20_p1_final.ipynb/' ./



# the red text is a placeholder! Change it to the name of this notebook!
!jupyter nbconvert --to PDF "4740_FA20_p1_final.ipynb"

"""# You are done! ✅"""